### ISSUE TITLE
Advanced Query Builder Filter

### ISSUE THREAD

**Issue by edwinmp** [devinit/ddw-analyst-ui#531]
We currently have the UI below:
![image](https://user-images.githubusercontent.com/5672438/119632342-630a2080-be19-11eb-921e-9cc43c2c3c96.png)

What's Missing:

- [x] Reset button - returns the filter editor to the default (depending on the selected AND/OR)
- [x] On adding a column filter, the value should be cleared
- [x] On replace/insert, validate the JSON before applying to main editor
- [ ] Clear all the tasks in the comments below

**Comment by edwinmp** [comment]
> * On adding a column filter, the value should be cleared

This one may not be clear ... In the screenshot below, when a filter is added by clicking the add button, the value field should be cleared & ready to take in new input.

NB: uploading screenshots has failed, so ask for a call so I can share my screen

**Comment by edwinmp** [comment]
We're going to need a new design for this ... the current one isn't as user friendly as I expected ... I'm open to suggestions. @davidebukali I remember you mentioned some kind of nested widget.

**TODO**

- [x] Design more intuitive UI for the filter helper
- [x] Implement filter helper UI

**Comment by edwinmp** [comment]
**BUG**

- [x] Filter validation doesn't not account for complex filter configs like the one below & instead returns a bunch of errors

```
{
  "$or": [
    {
      "$and": [
        {
          "column": "Donor",
          "comp": "$eq",
          "value": "Central Emergency Response Fund"
        },
        {
          "column": "Recipient.Organization",
          "comp": "$eq",
          "value": "World Food Programme"
        }
      ]
    },
    {
      "$and": [
        {
          "column": "Donor",
          "comp": "$eq",
          "value": "Japan, Government of"
        },
        {
          "column": "Recipient.Organization",
          "comp": "$eq",
          "value": "World Food Programme"
        }
      ]
    }
  ]
}
```

**Comment by edwinmp** [comment]
**BUG**

- [x] When the data source changes, any existing filter properties must be cleared

**Comment by edwinmp** [comment]
We're going to customise and use [this](https://querybuilder.js.org/demo.html) query builder for the filter.

**Comment by edwinmp** [comment]
We still have a PR open for this ... the updated design should help with ticket #580

**Comment by edwinmp** [comment]
**Behaviour Updates**

- [ ] Sort columns alphabetically

**What's Missing**

- [ ] Not Equal
- [ ] Less Than or Equal
- [ ] Great Than or Equal
- [ ] E.T.C - Basically, it can't do everything the current basic filter can do.
